# Generated by Django 5.1.2 on 2024-11-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='author',
            field=models.CharField(default='ritsuki', max_length=255, verbose_name='作成者'),
        ),
    ]
