# Generated by Django 5.1.2 on 2024-11-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_memo_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
