# Generated by Django 5.1.2 on 2024-11-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_memo_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='ユーザーネーム')),
                ('password', models.CharField(max_length=255, verbose_name='パスワード')),
            ],
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='memo',
        ),
    ]
